SCREEN_HEIGHT = 24
SCREEN_WIDTH = 79

GAME_TITLE_LINE1_X = 4
GAME_TITLE_LINE1_Y = 6
GAME_TITLE_LINE2_X = 33
GAME_TITLE_LINE2_Y = 12

ROUND_TITLE_LINE1_X = 14
ROUND_TITLE_LINE1_Y = 6
ROUND_TITLE_LINE2_X = 20
ROUND_TITLE_LINE2_Y = 12

FASTROUND_TITLE_LINE1_X = 20
FASTROUND_TITLE_LINE1_Y = 6
FASTROUND_TITLE_LINE2_X = 16
FASTROUND_TITLE_LINE2_Y = 12

ROUND_SCORE_X = 35
ROUND_SCORE_Y = 6

FASTROUND_SCORE_X = 67
FASTROUND_SCORE_Y = 19

TEAM_A_SCORE_X = 3
TEAM_A_SCORE_Y = 14

TEAM_B_SCORE_X = 67
TEAM_B_SCORE_Y = 14

QUESTION_MAX_WIDTH = 69
QUESTION_Y = 1

ANSWER_X = 13
ANSWER_Y = 10
ANSWER_COLS = 2
ANSWER_ROWS = 4
ANSWER_WIDTH = 25
ANSWER_HEIGHT = 3
ANSWER_DELAY = 1.5
ANSWER_ANIMATION_DELAY = 0.045

WRONG_ANSWER_Y = 12
WRONG_ANSWER_WIDTH = 9
WRONG_ANSWER_DELAY = 1.5
WRONG_ANSWER_MAX = 3

GUESS_X = 13
GUESS_Y = 7
GUESS_COLS = 2
GUESS_ROWS = 5
GUESS_WIDTH = 25
GUESS_HEIGHT = 3
GUESS_STEPS = 3
GUESS_DELAY = 0.015
